package DCMS;


/**
* DCMS/FrontEnd.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DCMS.idl
* Saturday, July 29, 2017 10:41:44 AM EDT
*/

public interface FrontEnd extends FrontEndOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FrontEnd
