package DCMS;

/**
* DCMS/FrontEndHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DCMS.idl
* Saturday, July 29, 2017 10:41:44 AM EDT
*/

public final class FrontEndHolder implements org.omg.CORBA.portable.Streamable
{
  public DCMS.FrontEnd value = null;

  public FrontEndHolder ()
  {
  }

  public FrontEndHolder (DCMS.FrontEnd initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DCMS.FrontEndHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DCMS.FrontEndHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DCMS.FrontEndHelper.type ();
  }

}
