package ClassManageSystem;


/**
* ClassManageSystem/CenterServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ClassManageSystem.idl
* Saturday, July 29, 2017 10:07:17 AM EDT
*/

public interface CenterServer extends CenterServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CenterServer
