package ClassManageSystem;


/**
* ClassManageSystem/CenterServerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ClassManageSystem.idl
* Saturday, July 29, 2017 10:07:17 AM EDT
*/

public abstract class CenterServerPOA extends org.omg.PortableServer.Servant
 implements ClassManageSystem.CenterServerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("createTRecord", new java.lang.Integer (0));
    _methods.put ("createSRecord", new java.lang.Integer (1));
    _methods.put ("getRecordCounts", new java.lang.Integer (2));
    _methods.put ("editRecord", new java.lang.Integer (3));
    _methods.put ("transferRecord", new java.lang.Integer (4));
    _methods.put ("shutdown", new java.lang.Integer (5));
    _methods.put ("getRecordInfo", new java.lang.Integer (6));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ClassManageSystem/CenterServer/createTRecord
       {
         String managerId = in.read_string ();
         String firstName = in.read_string ();
         String lastName = in.read_string ();
         String address = in.read_string ();
         String phone = in.read_string ();
         String specialization = in.read_string ();
         String location = in.read_string ();
         boolean $result = false;
         $result = this.createTRecord (managerId, firstName, lastName, address, phone, specialization, location);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // ClassManageSystem/CenterServer/createSRecord
       {
         String managerId = in.read_string ();
         String firstName = in.read_string ();
         String lastName = in.read_string ();
         String coursesRegistered = in.read_string ();
         String status = in.read_string ();
         String date = in.read_string ();
         boolean $result = false;
         $result = this.createSRecord (managerId, firstName, lastName, coursesRegistered, status, date);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // ClassManageSystem/CenterServer/getRecordCounts
       {
         String managerId = in.read_string ();
         String $result = null;
         $result = this.getRecordCounts (managerId);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // ClassManageSystem/CenterServer/editRecord
       {
         String managerId = in.read_string ();
         String recordID = in.read_string ();
         String fieldName = in.read_string ();
         String newValue = in.read_string ();
         boolean $result = false;
         $result = this.editRecord (managerId, recordID, fieldName, newValue);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 4:  // ClassManageSystem/CenterServer/transferRecord
       {
         String managerId = in.read_string ();
         String recordID = in.read_string ();
         String remoteCenterServerName = in.read_string ();
         boolean $result = false;
         $result = this.transferRecord (managerId, recordID, remoteCenterServerName);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 5:  // ClassManageSystem/CenterServer/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       case 6:  // ClassManageSystem/CenterServer/getRecordInfo
       {
         String recordID = in.read_string ();
         String $result = null;
         $result = this.getRecordInfo (recordID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ClassManageSystem/CenterServer:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public CenterServer _this() 
  {
    return CenterServerHelper.narrow(
    super._this_object());
  }

  public CenterServer _this(org.omg.CORBA.ORB orb) 
  {
    return CenterServerHelper.narrow(
    super._this_object(orb));
  }


} // class CenterServerPOA
